import * as React from 'react';
import { SiBitcoinsv } from 'react-icons/si';
import { LockLike } from '../types';
import { DEFAULT_LOCKLIKE_AMOUNT, DEFAULT_LOCKLIKE_BLOCKS } from '../types';

interface LockLikeInteractionProps {
  postTxid?: string;
  replyTxid?: string;
  postLockLike: (
    txid: string,
    amount: number,
    nLockTime: number,
    handle: string,
    postTxid?: string,
    replyTxid?: string
  ) => Promise<LockLike>;
}

export default function LockLikeInteraction({ postTxid, replyTxid, postLockLike }: LockLikeInteractionProps) {
  const [loading, setLoading] = React.useState(false);
  const [showInput, setShowInput] = React.useState(false);
  const [amount, setAmount] = React.useState(DEFAULT_LOCKLIKE_AMOUNT.toString());
  const [blocks, setBlocks] = React.useState(DEFAULT_LOCKLIKE_BLOCKS.toString());

  const handleLockLike = async () => {
    setLoading(true);
    try {
      const parsedAmount = parseFloat(amount);
      const parsedBlocks = parseInt(blocks);

      if (isNaN(parsedAmount) || parsedAmount <= 0) {
        throw new Error('Invalid amount');
      }

      if (isNaN(parsedBlocks) || parsedBlocks <= 0) {
        throw new Error('Invalid block count');
      }

      // Simulate the current block height
      const currentBlockHeight = 800000;
      const nLockTime = currentBlockHeight + parsedBlocks;

      await postLockLike(
        'generated_txid', // This would be generated by the wallet
        parsedAmount * 100000000, // Convert to satoshis
        nLockTime,
        'anon', // This would come from the wallet
        postTxid,
        replyTxid
      );

      setShowInput(false);
      setAmount(DEFAULT_LOCKLIKE_AMOUNT.toString());
      setBlocks(DEFAULT_LOCKLIKE_BLOCKS.toString());
    } catch (error) {
      console.error('Error locking:', error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex gap-0 relative items-center">
      {loading ? (
        <div role="status">
          <svg
            aria-hidden="true"
            className="inline w-4 h-4 mr-2 text-gray-200 animate-spin dark:text-gray-600 fill-orange-400"
            viewBox="0 0 100 101"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z"
              fill="currentColor"
            />
            <path
              d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z"
              fill="currentFill"
            />
          </svg>
          <span className="sr-only">Loading...</span>
        </div>
      ) : (
        <>
          <button
            onClick={() => setShowInput(!showInput)}
            className="flex items-center space-x-1 text-gray-600 dark:text-gray-400 hover:text-orange-500 dark:hover:text-orange-400"
          >
            <SiBitcoinsv className="h-4 w-4" />
            <span>Lock</span>
          </button>

          {showInput && (
            <div className="absolute top-8 left-0 bg-white dark:bg-gray-800 rounded-lg shadow-lg p-4 z-50 w-64">
              <div className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300">
                    Amount (BSV)
                  </label>
                  <input
                    type="number"
                    value={amount}
                    onChange={(e) => setAmount(e.target.value)}
                    className="mt-1 block w-full rounded-md border-gray-300 dark:border-gray-700 shadow-sm focus:border-orange-500 focus:ring-orange-500 bg-white dark:bg-gray-900 text-sm"
                    placeholder="0.00000000"
                    min="0"
                    step="0.00000001"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300">
                    Blocks
                  </label>
                  <input
                    type="number"
                    value={blocks}
                    onChange={(e) => setBlocks(e.target.value)}
                    className="mt-1 block w-full rounded-md border-gray-300 dark:border-gray-700 shadow-sm focus:border-orange-500 focus:ring-orange-500 bg-white dark:bg-gray-900 text-sm"
                    placeholder="1000"
                    min="1"
                  />
                </div>
                <button
                  onClick={handleLockLike}
                  className="w-full px-4 py-2 text-sm font-medium text-white bg-orange-500 rounded-lg hover:bg-orange-600 focus:outline-none focus:ring-2 focus:ring-orange-500 focus:ring-offset-2"
                >
                  Lock BSV
                </button>
              </div>
            </div>
          )}
        </>
      )}
    </div>
  );
} 